### ISSUE TITLE
dgd.exe.stackdump

### ISSUE THREAD

**Issue by seikichin** [dworkin/dgd#15]
I use gurbalib and the driver dump :
driver->binary_connect() did not return persistent object                5 [main] dgd 343 cygwin_exception::open_stackdumpfile: Dumping stack trace to dgd.exe.stackdump                                                                                                                                           C:\Users\Admini
I config local_config. h disable the ftp
like this:
define DISABLE_FTP 1 */
if anyone try to connect the 4001 port the driver will dump

**Comment by dworkin** [comment]
This is a gurbalib issue.  However, when you disable FTP you should also disable binary_port in the mud.dgd file:
```
binary_port = ([ ]);
```

**Comment by seikichin** [comment]
thanks a lot that is helpful


 
---Original---

**Comment by seikichin** [comment]
does dgd support text block
 for example£º
with fluffos I can draw a mice like this:
    set("long", @LONG
    
[37m     
         ,;;;.;,;;;;,,   _
      .;'             ''( );.
    .;'                    o,'.
         )       .  .        :;
   ::       ~     ~( ~'';,,;\~~
  : '. ,,, \'....; ',
 '        ..     ',,,'
;           ,,
,;;;'
[0m
LONG
        );


between @LONG  and  LONG is the text mice 






ÿ


---Original---

**Comment by shentino** [comment]
> does dgd support text block for example£º with fluffos I can draw a mice like this: set("long", @long [37m ,;;;.;,;;;;,, _ .;' ''( );. .;' o,'. ) . . :; :: ~ ~( ~'';,,;\~~ : '. ,,, \'....; ', ' .. ',,,' ; ,, ,;;;' [0m LONG ); between @long and LONG is the text mice ÿ
> […](#)
> ---Original--- From: "Felix A. Croes"<notifications@github.com> Date: Wed, Jul 24, 2019 02:42 AM To: "dworkin/dgd"<dgd@noreply.github.com>; Cc: "Author"<author@noreply.github.com>;"seikichin"<seikichin@qq.com>; Subject: Re: [dworkin/dgd] dgd.exe.stackdump (#15) Closed #15. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I think you should file this as a separate issue
