### ISSUE TITLE
separate issue

### ISSUE THREAD

**Issue by seikichin** [dworkin/dgd#16]
does dgd support text block for example£º with fluffos I can draw a mice like this: 
set("long", @LONG [37m ,;;;.;,;;;;,, _ .;' ''( );. .;' o,'. ) . . :; :: ~ ~( '';,,;~ : '. ,,, '....; ', ' .. ',,,' ; ,, ,;;;' [0m LONG ); between @LONG and LONG is the text mice

**Comment by seikichin** [comment]
[37m     
	         ,;;;.;,;;;;,,   _
	      .;'             ''( );.
	    .;'                    o,'.
	    ;     )       .  .  ;      :;
	   ::       ~     ~( ~'';,,;\~~
	  : '. ,,, \'....; ',
	 '        ;..     ',,,'
	;           ;,,
	,;;;'
[0

**Comment by seikichin** [comment]
something like ASCII art

**Comment by dworkin** [comment]
DGD of course supports ASCII art, but it doesn't support `@long` - `LONG` test blocks.  You can break up strings with a backslash:
```
set_long("long", "\
         ,;;;.;,;;;;,,   _\n\
      .;'             ''( );.\n\
    .;'                    o,'.\n\
         )       .  .        :;\n\
   ::       ~     ~( ~'';,,;\~~\n\
  : '. ,,, \'....; ',\n\
 '        ..     ',,,'\n\
;           ,,\n\
,;;;'\n\
");
```

**Comment by seikichin** [comment]
thank you for the reply



---Original---

**Comment by seikichin** [comment]
I use gurblib and I got an error: 
Compiler error:
Sun Aug  4 20:55:55 2019:smaug:/domains/test/rooms/mice_room2.c, 8:
unterminated unterminated string
illegal
character: '.'
syntax
error 
illegal
character: '\'

**Comment by seikichin** [comment]
#include "../../domain.h"
inherit "/std/room";
void setup(void) { 


set_short("mice room" );
set_long("\
         ,;;;.;,;;;;,,   _\n\
      .;'             ''( );.\n\
    .;'                    o,'.\n\
         )       .  .        :;\n\
   ::       ~     ~( ~'';,,;\~~\n\
  : '. ,,, \'....; ',\n\
 '        ..     ',,,'\n\
;           ,,\n\
,;;;'\n\
");
 set_exits((["down": DIR + "/mice_room3",]) );
 
    }

**Comment by dworkin** [comment]
You have to use a backslash at the end of the lines, exactly as in my example.

**Comment by seikichin** [comment]
I copy your example and it doesn't work



---Original---

**Comment by Blain20** [comment]
Change the line endings for your source file to Unix style.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by seikichin** [comment]
Good it works ！thank you！



---Original---
