### ISSUE TITLE
features wanted

### ISSUE THREAD

**Issue by seikichin** [dworkin/dgd#17]
how about make a feature to support text block like：
@HereDoc some texts @HereDoc
no matter what between @HereDoc are texts.  This feature is more convenient.

**Comment by quixadhal** [comment]
Nothing prevents you from either modifying the DGD grammar to accomplish this yourself, or simply putting your pre-formatted stuff in files and having your code read them in when the object is created, if you really don’t want to type a bunch of backslashes.  The read_file() kfun is pretty easy to use.

Sent from Mail for Windows 10

From: seikichin
Sent: Wednesday, August 7, 2019 1:30 AM
To: dworkin/dgd
Cc: Subscribed
Subject: [dworkin/dgd] features wanted (#17) 

how about make a feature to support text block like：
@Heredoc some texts @Heredoc
no matter what between @Heredoc are texts. This feature is more convenient.

**Comment by seikichin** [comment]
thank you let me have try the read_file



---Original---

**Comment by dworkin** [comment]
I am not planning to add such string blocks to the the language, there are many alternative solutions already available.
