### ISSUE TITLE
Problem creating directories

### ISSUE THREAD

**Issue by Blain20** [dworkin/dgd#20]
I'm suddenly having a problem saving using save_object().  It's the line in file.c which says "Cannot create temporary save file "<file>".  The path it shows is valid.  DGD has no problem writing to disk with write_file().  I don't know if I changed something, but all my code looks good.  It behaves the same with version 1.6.3 and 1.6.9 (I have just moved to the latter).  I'm using LINUX host option on Cygwin on Win 8.1.  I'm not sure where else to look.

**Comment by Blain20** [comment]
Update:  Win 8.1 somehow garbled permissions for subdirs under /dat/usr/, likely when I had DGD create the subdirs for a new user.  I'll try to recreate it again.  I fixed the problem by forcing the /dat/ directory's permission setup onto its children recursively.

**Comment by Blain20** [comment]
Update:  Having DGD create a directory is creating one with misordered permissions, according to Win 8.1.  I'm looking into it to see if my perms are confusing it or if it would always do this regardless of my initial setup.

**Comment by dworkin** [comment]
I'm not sure why the permissions of directories would suddenly be wrong.  Is there an older version of DGD that you've used which doesn't have this behaviour?

**Comment by Blain20** [comment]
I have never seen this behavior before.  I forced perms on the binary and tried it.  It's still making weird perms on the new directories, but it's not locking DGD out of write permission during save_object.  At this point, I'm laying blame on Windows.  DGD should be fine, I suppose.  save_object seems to be passing more flags during save_object than write_file, so that made me initially think DGD was being weird.  I imagine write_file could be silently failing at times and my lib isn't set up to complain.  I guess you can close the issue.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
