### ISSUE TITLE
Could an example be added how to start/initialize DGD for a custom MUD?

### ISSUE THREAD

**Issue by rubyFeedback** [dworkin/dgd#22]
Hey Felix,

Not sure if you have enough time (compared to the oldschool 1990s :-) ) but I have had some
experience writing in LPC, even though I use other languages these days (evidently ruby).

Without making this issue too long, would you think it to be possible to specifically add a file
here, a markdown file, that would help in setting up DGD from scratch on a given linux
system? Just an example file what steps are necessary; does not have to be detailed,
just so that people could quickly get started with it. For some folks (including myself here)
it's difficult to work through documentation without examples as-is.

The name of the fool could be setup.md or something, in doc/. THere is already
a file called Compiling, so perhaps another one, .md could be added like ...
dunno... setup or bootstrapping or starting a MUD, or perhaps an example
MUD. https://github.com/dworkin/dgd/blob/master/doc/Compiling

**Comment by seikichin** [comment]
You need this https://github.com/sirdude/gurbalib.git

**Comment by dworkin** [comment]
Documentation for people who don't read documentation?

Setting up DGD from scratch on a linux system just involves typing "make" in the dgd/src directory. If you want it to do anything useful, you also need a MUD library written for DGD, such as the aforementioned Gurbalib. Those come with their own installation instructions.

**Comment by shentino** [comment]
Indeed.

I would also like to point out that the DGD ecosystem, as it were, is layered.  I recently documented these layers for Skotos.

Each layer has its own selection of software and potentially hardware to choose from.  Each choice of which has its own instructions, which need to be followed in series.  Each layer on its own though is fairly simple.

For starters you need a standard OS that has a developer suite capable of compiling DGD itself.  Linux tends to be most convenient for this (you will need yacc, cc, and make), but you can also do it on Windows.  This optionally includes the usage of extensions for DGD itself.

The config file specified on the command line will spell out the rest and should conform to the instructions given by your mudlib.

Where you go from here is completely up to you.

There are a few codebases out there that depend on lower layered codebases some of which are maintained by different developers.  An example is that a few mudlibs out there are dependent on the kernel library.  SkotOS itself has a slightly modified version included.

Documentation for using DGD proper is included in the lpc-doc package and some within DGD itself.  Read those and the documentation for the mudlib in question and you should be good to go.

**Comment by dworkin** [comment]
Closing this; @rubyFeedback seems to be a serial one-shot issue poster unwilling to clarify. Documentation remains an ongoing concern and will probably have its future issue(s).
