### ISSUE TITLE
Question: Disabling -DDEBUG

### ISSUE THREAD

**Issue by shentino** [dworkin/dgd#25]
Is there any problem, either with functionality or with being supported, if I remove -DDEBUG from Makefile before compiling DGD?

For example I noticed in endtask() that it seems to always force a swapout and I'd rather not face the performance penalty

**Comment by dworkin** [comment]
As the name implies, it enables extra debugging.  That is all it does.

**Comment by shentino** [comment]
Is there any detriment on your end if I disable it?  I did become curious why you enabled it by default in commit 08959b5e45895e91f79345838681ac1600688854 dated Sep 24 20:27:22 2013

**Comment by dworkin** [comment]
You can do anything you like to a private copy of the repository.
