### ISSUE TITLE
Statedump/restore type-size-check logic doesn't work for a length of 8 in upper nybble of size fields.

### ISSUE THREAD

**Issue by noahgibbs** [dworkin/dgd#34]
In config.cpp, in Config::restore, there's a line that sets rtsize:

    rtsize = rheader.utsize >> 4;

Unfortunately, rheader.utsize is a signed character. So if the upper nybble (the UIndex size) is 8 or higher, utsize is considered negative and rtsize will be as well. One fix would be to change the line to cast to unsigned char:

    rtsize = ((unsigned char)rheader.utsize) >> 4;

It's possible that it should/could just be an unsigned char in SnapshotInfo, though. The same problem would occur with the EIndex size if it were 8, though that seems less likely.

I found this because I didn't realize "unsigned long" was 8 bytes on my Mac. So for now I'm fixing this by changing to an "unsigned int", which is plenty big enough for me right now.

**Comment by dworkin** [comment]
This is just one of the many places where things go wrong if you make `ssizet` (length of string) an 8 byte quantity. DGD is not prepared for this at all. There are warnings about it in `config.h`. So while technically you are correct that those 4 bits can contain the number 8, this must not happen.

It is a pity that SkotOS predates light-weight object support in DGD. There are definite drawbacks to juggling byte arrays larger than 64K, and it would be better to handle strings with an ADT, as I did [here](https://github.com/dworkin/cloud-server/blob/master/src/lib/String.c).

**Comment by noahgibbs** [comment]
Fair enough.

**Comment by dworkin** [comment]
I will update this code when I implement 8 byte integer support for DGD.  Hydra already has it.
