### ISSUE TITLE
Function parameters incorrectly failed by Frame::typecheck()

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#35]
With -DCLOSURE enabled, `function` parameters don't work in some scenarios due to `Frame::typecheck()` (giving an error message like "Bad object argument 1 for function call" depending of course which parameter receives the function pointer).

I was able to recreate this using a fresh install of cloud-server, with the following two files:

/usr/admin/send.c
```
mixed sample()
{
    return 42;
}

mixed send_f(function f)
{
    return "caller"->call(f);
}

mixed send_sample()
{
    return send_f(&sample());
}
```

/usr/admin/caller.c
```
mixed call(function f)
{
    return (*f)();
}
```

And logging in as admin, compiling the two objects and running `code "send"->send_sample()`.

It seems to be caused by commit fc3b76ed890290a80690129375006aada7005658 where `i_classname(prog_f, sclass)` became `className(sclass)` calling it from the running frame rather than the new frame. Changing this to `f->className(sclass)` fixed it for me.

**Comment by dworkin** [comment]
Confirmed and merged, thanks!
