### ISSUE TITLE
Stack smashing in 1.6.15?

### ISSUE THREAD

**Issue by shentino** [dworkin/dgd#37]
For some reason dgd's started crashing with a GCC assert about stack smashing.

Reproduction kit will be sent shortly.  See included reproduce.txt for further instructions

A back trace, predictably, could not be recovered

**Comment by shentino** [comment]
Of note this has happened before, but I ignored it because it was a fluke and I suspected a corrupted snapshot, but this time it's happening reliably with this kit.

Previous time, as this time, was triggered by a global recompile

**Comment by shentino** [comment]
I also noticed that a global rebuild seems to not crash it if there aren't any compilation failures, but I'm not 100 percent sure about this being a factor.

**Comment by dworkin** [comment]
Should be fixed by 53a0e1ca0f9f6309fdf0f10af0011787cd8103ca.

**Comment by shentino** [comment]
Fix confirmed
