### ISSUE TITLE
32-bit epoch compliance?

### ISSUE THREAD

**Issue by shentino** [dworkin/dgd#38]
The year 2038 problem is on the horizon so I was curious what DGD will be doing in this, if anything, to handle 32-bit wraparound once time() presumably becomes negative, and what ctime() will be doing to interpret it.

Out of curiosity, what's on the drawing board?

**Comment by dworkin** [comment]
The year 2038 problem has been on the horizon for a long time, and it was handled more than 20 years ago.

```
> code ctime(0x80800000)
$170 = "Mon Apr 26 07:24:16 2038"
> code ctime(0xffffffff)
$171 = "Sun Feb  7 07:28:15 2106"
```

**Comment by shentino** [comment]
> The year 2038 problem has been on the horizon for a long time, and it was handled more than 20 years ago.
> 
> ```
> > code ctime(0x80700000)
> $170 = "Wed Apr 14 04:08:00 2038"
> > code ctime(0xffffffff)
> $171 = "Sun Feb  7 07:28:15 2106"
> ```

My mistake should have done my homework.
