### ISSUE TITLE
rename_file() works in atomic function

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#39]
I'm able to call rename_file() in an atomic function, even one that immediately fails, for example using a function like below:

```
atomic void test(string a, string b, int fail)
{
	rename_file(a, b);
	if (fail) {
		error("fail");
	}
}
```

I'm able to reproduce this on the latest checkout of dgd running a clean checkout of Cloud Server.

I've written a local change that resolves this, I'll make a pull request so you can take a look.

**Comment by dworkin** [comment]
Thanks!
