### ISSUE TITLE
Casting string to float with 'e' exponent component

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#41]
When converting a string to a float with an exponent E (eg. 42e+9), Float::atof() is very permissive of what the first character can be after that 'e'/'E'.

For example `(float) "42ea"` produces `4.2e+50`, and `({ sscanf("42ea b", "%f%s", a, b), a, b })` returns `({ 2, 4.2e+50, " b"})` (note sscanf() internally uses the same Float::atof()).

The LPC compiler will treat `42ea` as error (that is, it treats the "ea" portion as a separate token which then fails), so I'd expect casting strings to do the same. Likewise, I'd expect the latter expression to instead return `({ 2, 42.0, "ea b" })`.

I've written a possible solution to this to help identify where the issue is.

(As usual, above was tested using latest dgd + cloud server, and can be tested through admin 'code' command.)

**Comment by dworkin** [comment]
Your analysis is correct and your fix is good, but incomplete (details in the pull request comments).

While looking into this, I found another issue with float parsing, which is now fixed in the master branch.
