### ISSUE TITLE
Connection::select issue after hotbooting

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#51]
This was another difficult one to track down, and frankly I'm still not convinced I understand it all the way. I have only experienced this on Linux, I don't know if it happens on Windows too since I don't have a Windows machine to test on right now.

Sometimes when a hotboot fails (for example, the executable configured to run is wrong, e.g. you typo "dgd" as "dgdg" and no such file exists), the following start up will read the file descriptors thinking that it's still hotbooting, and attempt to read from them.

Because `Connection::select()` treats error states as if there is nothing to read, and because linux's `select()` will return -1 in an error state without giving any further details beyond what's in `errno`, a single bad fd will prevent reading any other fds indefinitely.

Personally, I believe this is two issues. First, that the following startup is using that list of file descriptors incorrectly believing it's part of a hotboot, and second, that a single bad file descriptor can cause the whole `select()` to fail without ever self-correcting.

I haven't done enough analysis into why the former is happening, but as for the latter, since this problem can be identified: `select()` would return `-1` which is already being checked, `errno` should be set to `EBADF`, and it's possible to pinpoint precisely which file descriptor is unreadable (although `select()` itself could serve this purpose, I've seen `fcntl()` using one of its read-only operations suggested for this), it would make sense to me to add some error handling logic here.

If you want, I can write something for this and submit it in a pull request. I wanted to get your input before going any further though. I did write a patch that does the same on `Comm::restore()` which does resolve this issue, but I'm not sure if it's the ideal solution to put it there. I think a fix that's specific to the hotbooting side of the issue should probably be addressed at the point where it's determining whether a hotboot happened or not, not all the way in `Comm::restore()`, and likewise a fix addressing bad fds in general should probably go in `Connection::select()`'s error handling branch (which already exists but, as stated above, treats this outcome as if `select()` reported that nothing is ready to be read).

As an aside, even beyond not being able to confirm whether this is happening on Windows or not, I'm not even able to fully confirm that this is a widespread issue on Linux. On one machine in a fresh environment, a single bad fd dirties the state indefinitely, whereas on another machine with an older environment running for the past couple months, it only dirties the state for a single restart, so restarting it again is sufficient to clear the problem. I'm also not sure if this is the only root cause that can cause `select()` to fail, as I've had this happen numerous sporadic times.

**Comment by dworkin** [comment]
Should be fixed by 4dfb2941ab66c52b3c72a9b2669b258652f945c4. Doesn't apply to Windows, since hotbooting is not supported on Windows.

**Comment by dworkin** [comment]
As you see, I have a different opinion about where the first issue should be solved.  This was my original design for Hydra, which I accidentally left out when I later copied the functionality to DGD.

The second issue I don't see as significant -- select doesn't need to "recover" from bad file descriptors when there are no bad file descriptors.

**Comment by nyankers** [comment]
Ah, I see now. For some reason I got `Comm::restore()` mixed up and thought it was called _after_ determining the system had hotbooted. Woops. That's pretty much the ideal place to put it, yeah, haha.

For the second issue, I'm personally content with just adding a perror() there for now. Pretty much all I'm doing is storing errno in a variable, and printing out perror() on changes. God help me if it ever flip-flops somehow.

Thanks!
