### ISSUE TITLE
Segmentation fault on module call out of ticks

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#62]
Hi! I'm not sure if this is specifically an issue related to module calls, but I haven't been able to reproduce it with anything else so far. It can be recreated by adding the crypto module and running the following code (`/usr/admin/test.c`):
```
mixed test()
{
	int i;
	for (i=1000000; i--;) {
		hash_string("MD5", "foo");
	}
}
```

And then as admin:
```
compile test.c
code "/usr/admin/test" -> test()
```

I have noticed that it seems like it will not always fail. This seems to be random, meaning I've called the function and it somehow worked (that is, correctly gave an "out of ticks" error without crashing), but then the next time it failed.

It seems to happen due to an "out of ticks" error, so the above assumes default Cloud Server settings for tick limits.

**Comment by dworkin** [comment]
Should be fixed by the latest commit.

**Comment by nyankers** [comment]
Looks like it is, thanks! Happy New Year by the way. <3

**Comment by dworkin** [comment]
Happy New Year.
