### ISSUE TITLE
ftoi() broke for negative numbers

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#65]
Hi! The recent LPCINT changes seem to have broken, for example, `(int) -5.0`.

The exact troublesome line seems to be from `hostfloat.cpp:327`:

```
	if (a < (double) LPCINT_MIN) {
```

`LPCINT_MIN` is `0x80000000L` which I think is treated as a positive literal.

One possible fix would be casting `LPCINT_MIN` to the signed `LPCint` type before casting it to a double, e.g.

```
	if (a < (double) ((LPCint) LPCINT_MIN)) {
```

But I'll leave the actual fix up to you, since you know what this constant's intended uses are better than I do (though it looks like you're doing the same work I started doing when fiddling with a 64-bit LPC, aha...)

**Comment by dworkin** [comment]
Your suggested fix is correct, but there was another instance where the same mistake was made.  Both should be fixed by the latest commit.

**Comment by nyankers** [comment]
Looks like it works, yeah. Mostly, I was wondering if you might actually want to put it in the `#define` statement itself or use a `const` or something like that. :)

Thank you! <3
