### ISSUE TITLE
-DLARGENUM issues

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#76]
Hi,

I've noticed that `random()` doesn't work right with numbers larger than 32-bit. For example, `random(8589934592)` produces only either `0` or `8589934592`. This seems to just be a typo on line 398 of `kfun/random.cpp`, using `&` instead of `%`.

Also, external modules have issues when this flag is enabled, though it seems like they might be resolved just by changing `LPC_int` from `uint32_t` to `uint64_t` when compiling the modules to match DGD, so perhaps this is better addressed on lpc-ext. For my local, I've added a similar `LARGENUM` flag that I'm checking to determine which type `LPC_int` should be.

**Comment by dworkin** [comment]
> I've noticed that `random()` doesn't work right with numbers larger than 32-bit. For example, `random(8589934592)` produces only either `0` or `8589934592`. This seems to just be a typo on line 398 of `kfun/random.cpp`, using `&` instead of `%`.

Should be fixed by the [latest commit](https://github.com/dworkin/dgd/commit/b0cbc50844e091f83bcd8b2a8a6a8fc7989812d8).

> Also, external modules have issues when this flag is enabled, though it seems like they might be resolved just by changing `LPC_int` from `uint32_t` to `uint64_t` when compiling the modules to match DGD, so perhaps this is better addressed on lpc-ext. For my local, I've added a similar `LARGENUM` flag that I'm checking to determine which type `LPC_int` should be.

Interesting. External modules were intended not to require recompilation for different integer sizes, but this was an oversight. I had intended that integers in the module interface should always be 32 bits, but perhaps it's time to reconsider.

**Comment by dworkin** [comment]
Yes, I originally took the decision to standardize on 32 bit `LPC_int` before there was a JIT compiler.  Now that there is, and given that JIT-compiled code always has to follow DGD's model, it doesn't make sense to have two different notions of LPC integers in the extension interface.

**Comment by nyankers** [comment]
JIT _seemed_ to be working fine with a 32-bit build, though it's hard to tell if there were hidden issues. However, I did notice that having JIT on changed some behavior with module kfuns. With JIT on, integers outside the 32-bit range became 0, whereas with JIT off, they wrapped around.

Either way, though, negative integers were treated as positive integers with 32-bit modules. I noticed it right away since my bizarre color engine uses negative numbers as magic numbers.

Recompiling the modules as 64-bit seems to have solved all of the above.

**Comment by dworkin** [comment]
The extension module interface now has official LARGENUM support, including the JIT compiler.
```
make DEFINES=-DLARGENUM
```

**Comment by nyankers** [comment]
These changes seem to be working. Thanks! ^^

**Comment by nyankers** [comment]
Also thanks for adding 64-bit support!

I tried my hand at it a while ago, but ran into some issues and never finished working on it. ^^;
