### ISSUE TITLE
JIT causes termination 

### ISSUE THREAD

**Issue by nyankers** [dworkin/dgd#78]
Running the following LPC code in JIT:

```
int test(object obj) {
    if (obj <- "/lib/Time") {
        return TRUE;
    }
    return FALSE;
}
```

Causes the following error if `obj` is `nil`:

```
terminating with uncaught exception of type char const*
```

This doesn't happen outside of JIT, so testing this requires some shenanigans to ensure it's JIT compiled. Assuming the above LPC is in `test.c`:

```
compile test.c
compile test.c
code "test"->test(nil)
code "test"->test(nil)
```

**Comment by dworkin** [comment]
Should be fixed by 5117da4.
