### ISSUE TITLE
get_dir gets confused if a file has the same name as the directory it is in.

### ISSUE THREAD

**Issue by knubo** [dworkin/dgd#86]
It appears that if you do:

get_dir("/players/knubo/tmp")

It will return:

    ({ /* sizeof() == 1 */
        tmp
    }),
    ({ /* sizeof() == 1 */
        -2
    }),
    ({ /* sizeof() == 1 */
        1705694168
    }),

If you add a file called tmp, in this directory, it will start reporting:

    ({ /* sizeof() == 1 */
        tmp
    }),
    ({ /* sizeof() == 1 */
        0
    }),
    ({ /* sizeof() == 1 */
        1705694493
  
This appears to be a change from eariler version of DGD. We're currently at 1.7.1 (migrated today) when we found it on connect.vikingmud.org 2001.

Best regads, Knubo

**Comment by dworkin** [comment]
Should be fixed by 4578348154bfa2994c3d5e051d0c67e885087ca5.

**Comment by knubo** [comment]
Can confirm that with this patch this get_dir bug is gone.
