### ISSUE TITLE
switch will not match case single item statements in some cases.

### ISSUE THREAD

**Issue by knubo** [dworkin/dgd#87]
The following code does not match 0 in the switch.

```
int bink() {
  int size, i;
  object ob;
  string sizestr;

  sizestr = "Change me";
  
  size = 0;
  switch (size) {
  case 0:
    sizestr = "tiny ";
    break;
  case 1: sizestr = "little "; break;
  case 2: sizestr = "small "; break;
  case 3..5: sizestr = ""; break;
  case 6: sizestr = "large "; break;
  case 7: sizestr = "big "; break;
  case 8: sizestr = "huge "; break;
  }


  write("Huh:"+sizestr+"\n");
  return size;
}
```

Whereas a much simpler case do work:
```

void working_switch() {
  int s,i;
  string x;

  s = 0;

  switch(s) {
  case 0:
    x = "0 case";
    break;
  case 1:
    write("Huh\n");
    break;
  }

  write(x);
}

```

Found on Viking.

**Comment by geirpg** [comment]
Further investigation of the bug: 
 * It only appears when you mix singular values and ranges.
 * Ranges such as 1..1 still bugs
 * It only affects the 0 case. Other cases work as expected.
 * If you have no "case 0" everything works as expected as well.

**Comment by dworkin** [comment]
It looks like this happens when DGD converts a range switch into an int switch.

**Comment by dworkin** [comment]
This was broken by my solution for issue #70. I have a fix, I'll push it when I have the opportunity.

**Comment by dworkin** [comment]
Should be fixed by b28cea435a3f9be2bfc7891c8e924b82e926a69a.

**Comment by knubo** [comment]
The mud now went down with an exit code of 134. Is it possible that this fix creates a pointer problem?

**Comment by dworkin** [comment]
Exit code 134 indicates that it ended with an abort, not with a segmentation fault.  Was there anything in the log?

**Comment by geirpg** [comment]
So. We have two log entries, from our driver logs:
2024-01-21 14:05:40 viking-test startmud[107633] Driver went down with exit code 134
and in the driver error log:
Fatal error: cannot create swap file "/run/shm/viking-swap"

Looks fairly local to me, but haven't been able to confirm with server root.

**Comment by dworkin** [comment]
`/var/shm/viking-swap` but the the grep finds `/dev/shm`, not `/var/shm`.  This must have been an issue with the previous DGD version 1.4.* also?

**Comment by knubo** [comment]
We haven't had the test mud running on this host for long.

ed_tmpfile	= "/run/shm/viking-ed";	/* proto editor tmpfile */
swap_file	= "/run/shm/viking-swap";	/* swap file */

So we should point these to /dev/shm? Not /run/shm?

**Comment by dworkin** [comment]
Going by the abort error message, `/run/shm` does not even exist.  So yes, change it to '/dev/shm`.

**Comment by dworkin** [comment]
I assume that both the `switch` issue and the fatal swap file problem have been solved.

**Comment by geirpg** [comment]
Yes. We're running 1.7.1 completely stable and error free now. Thank you for swift response and fix.

**Comment by dworkin** [comment]
Excellent.  I will wrap up those fixes in a new release.
